namespace T2
{
    partial class Form3
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form3));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuNumberlbl = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuNamelbl = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.maskedTextBox1 = new System.Windows.Forms.MaskedTextBox();
            this.bunifuMaillbl = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuSavebtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuMail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuSurnamelbl = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuTextBox1 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.guna2AnimateWindow1 = new Guna.UI2.WinForms.Guna2AnimateWindow(this.components);
            this.dateTimePicker1 = new System.Windows.Forms.DateTimePicker();
            this.listBox1 = new System.Windows.Forms.ListBox();
            this.bunifuFileNametxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLoadbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuAddbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuModifybtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuClearbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.examplelbl = new Bunifu.UI.WinForms.BunifuLabel();
            this.SuspendLayout();
            // 
            // bunifuNumberlbl
            // 
            this.bunifuNumberlbl.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
            this.bunifuNumberlbl.AllowParentOverrides = false;
            this.bunifuNumberlbl.AutoEllipsis = false;
            this.bunifuNumberlbl.AutoSize = false;
            this.bunifuNumberlbl.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(10)))), ((int)(((byte)(17)))), ((int)(((byte)(40)))));
            this.bunifuNumberlbl.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.bunifuNumberlbl.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.bunifuNumberlbl.CursorType = null;
            this.bunifuNumberlbl.Font = new System.Drawing.Font("Segoe UI Black", 15.75F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuNumberlbl.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(130)))), ((int)(((byte)(162)))));
            this.bunifuNumberlbl.Location = new System.Drawing.Point(22, 338);
            this.bunifuNumberlbl.Name = "bunifuNumberlbl";
            this.bunifuNumberlbl.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuNumberlbl.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuNumberlbl.Size = new System.Drawing.Size(97, 37);
            this.bunifuNumberlbl.TabIndex = 0;
            this.bunifuNumberlbl.Text = "Number";
            this.bunifuNumberlbl.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuNumberlbl.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuNumberlbl.Click += new System.EventHandler(this.bunifuMaillbl_Click_1);
            // 
            // bunifuNamelbl
            // 
            this.bunifuNamelbl.AllowParentOverrides = false;
            this.bunifuNamelbl.AutoEllipsis = false;
            this.bunifuNamelbl.AutoSize = false;
            this.bunifuNamelbl.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(10)))), ((int)(((byte)(17)))), ((int)(((byte)(40)))));
            this.bunifuNamelbl.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.bunifuNamelbl.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.bunifuNamelbl.CursorType = null;
            this.bunifuNamelbl.Font = new System.Drawing.Font("Segoe UI Black", 15.75F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuNamelbl.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(130)))), ((int)(((byte)(162)))));
            this.bunifuNamelbl.Location = new System.Drawing.Point(22, 19);
            this.bunifuNamelbl.Name = "bunifuNamelbl";
            this.bunifuNamelbl.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuNamelbl.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuNamelbl.Size = new System.Drawing.Size(81, 37);
            this.bunifuNamelbl.TabIndex = 0;
            this.bunifuNamelbl.Text = "Name";
            this.bunifuNamelbl.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuNamelbl.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.AutoSize = false;
            this.bunifuLabel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(10)))), ((int)(((byte)(17)))), ((int)(((byte)(40)))));
            this.bunifuLabel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.bunifuLabel1.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.bunifuLabel1.CursorType = null;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI Black", 15.75F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(130)))), ((int)(((byte)(162)))));
            this.bunifuLabel1.Location = new System.Drawing.Point(22, 125);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(111, 37);
            this.bunifuLabel1.TabIndex = 0;
            this.bunifuLabel1.Text = "Surname";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // maskedTextBox1
            // 
            this.maskedTextBox1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(226)))), ((int)(((byte)(133)))));
            this.maskedTextBox1.BeepOnError = true;
            this.maskedTextBox1.Font = new System.Drawing.Font("Microsoft Sans Serif", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.maskedTextBox1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(41)))), ((int)(((byte)(54)))));
            this.maskedTextBox1.HidePromptOnLeave = true;
            this.maskedTextBox1.Location = new System.Drawing.Point(25, 383);
            this.maskedTextBox1.Mask = "(+000) 00-0000000";
            this.maskedTextBox1.Name = "maskedTextBox1";
            this.maskedTextBox1.Size = new System.Drawing.Size(275, 31);
            this.maskedTextBox1.TabIndex = 4;
            // 
            // bunifuMaillbl
            // 
            this.bunifuMaillbl.AllowParentOverrides = false;
            this.bunifuMaillbl.AutoEllipsis = false;
            this.bunifuMaillbl.AutoSize = false;
            this.bunifuMaillbl.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(10)))), ((int)(((byte)(17)))), ((int)(((byte)(40)))));
            this.bunifuMaillbl.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.bunifuMaillbl.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.bunifuMaillbl.CursorType = null;
            this.bunifuMaillbl.Font = new System.Drawing.Font("Segoe UI Black", 15.75F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuMaillbl.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(130)))), ((int)(((byte)(162)))));
            this.bunifuMaillbl.Location = new System.Drawing.Point(22, 231);
            this.bunifuMaillbl.Name = "bunifuMaillbl";
            this.bunifuMaillbl.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuMaillbl.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuMaillbl.Size = new System.Drawing.Size(81, 37);
            this.bunifuMaillbl.TabIndex = 0;
            this.bunifuMaillbl.Text = "Email";
            this.bunifuMaillbl.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuMaillbl.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuMaillbl.Click += new System.EventHandler(this.bunifuLabel2_Click);
            // 
            // bunifuSavebtn
            // 
            this.bunifuSavebtn.AllowAnimations = true;
            this.bunifuSavebtn.AllowMouseEffects = true;
            this.bunifuSavebtn.AllowToggling = false;
            this.bunifuSavebtn.AnimationSpeed = 200;
            this.bunifuSavebtn.AutoGenerateColors = false;
            this.bunifuSavebtn.AutoRoundBorders = true;
            this.bunifuSavebtn.AutoSizeLeftIcon = true;
            this.bunifuSavebtn.AutoSizeRightIcon = true;
            this.bunifuSavebtn.BackColor = System.Drawing.Color.Transparent;
            this.bunifuSavebtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(130)))), ((int)(((byte)(162)))));
            this.bunifuSavebtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSavebtn.BackgroundImage")));
            this.bunifuSavebtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuSavebtn.ButtonText = "Save";
            this.bunifuSavebtn.ButtonTextMarginLeft = 0;
            this.bunifuSavebtn.ColorContrastOnClick = 45;
            this.bunifuSavebtn.ColorContrastOnHover = 45;
            this.bunifuSavebtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuSavebtn.CustomizableEdges = borderEdges1;
            this.bunifuSavebtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuSavebtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuSavebtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuSavebtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuSavebtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuSavebtn.Font = new System.Drawing.Font("Segoe UI", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuSavebtn.ForeColor = System.Drawing.Color.White;
            this.bunifuSavebtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuSavebtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuSavebtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuSavebtn.IconMarginLeft = 11;
            this.bunifuSavebtn.IconPadding = 10;
            this.bunifuSavebtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuSavebtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuSavebtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuSavebtn.IconSize = 25;
            this.bunifuSavebtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuSavebtn.IdleBorderRadius = 54;
            this.bunifuSavebtn.IdleBorderThickness = 1;
            this.bunifuSavebtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(130)))), ((int)(((byte)(162)))));
            this.bunifuSavebtn.IdleIconLeftImage = null;
            this.bunifuSavebtn.IdleIconRightImage = null;
            this.bunifuSavebtn.IndicateFocus = false;
            this.bunifuSavebtn.Location = new System.Drawing.Point(847, 479);
            this.bunifuSavebtn.Name = "bunifuSavebtn";
            this.bunifuSavebtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuSavebtn.OnDisabledState.BorderRadius = 1;
            this.bunifuSavebtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuSavebtn.OnDisabledState.BorderThickness = 1;
            this.bunifuSavebtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuSavebtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuSavebtn.OnDisabledState.IconLeftImage = null;
            this.bunifuSavebtn.OnDisabledState.IconRightImage = null;
            this.bunifuSavebtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuSavebtn.onHoverState.BorderRadius = 1;
            this.bunifuSavebtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuSavebtn.onHoverState.BorderThickness = 1;
            this.bunifuSavebtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuSavebtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuSavebtn.onHoverState.IconLeftImage = null;
            this.bunifuSavebtn.onHoverState.IconRightImage = null;
            this.bunifuSavebtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuSavebtn.OnIdleState.BorderRadius = 1;
            this.bunifuSavebtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuSavebtn.OnIdleState.BorderThickness = 1;
            this.bunifuSavebtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(130)))), ((int)(((byte)(162)))));
            this.bunifuSavebtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuSavebtn.OnIdleState.IconLeftImage = null;
            this.bunifuSavebtn.OnIdleState.IconRightImage = null;
            this.bunifuSavebtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuSavebtn.OnPressedState.BorderRadius = 1;
            this.bunifuSavebtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuSavebtn.OnPressedState.BorderThickness = 1;
            this.bunifuSavebtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuSavebtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuSavebtn.OnPressedState.IconLeftImage = null;
            this.bunifuSavebtn.OnPressedState.IconRightImage = null;
            this.bunifuSavebtn.Size = new System.Drawing.Size(77, 56);
            this.bunifuSavebtn.TabIndex = 11;
            this.bunifuSavebtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuSavebtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuSavebtn.TextMarginLeft = 0;
            this.bunifuSavebtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuSavebtn.UseDefaultRadiusAndThickness = true;
            this.bunifuSavebtn.Click += new System.EventHandler(this.bunifuSavebtn_Click);
            // 
            // bunifuMail
            // 
            this.bunifuMail.AcceptsReturn = false;
            this.bunifuMail.AcceptsTab = false;
            this.bunifuMail.AnimationSpeed = 200;
            this.bunifuMail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuMail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuMail.BackColor = System.Drawing.Color.Transparent;
            this.bunifuMail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuMail.BackgroundImage")));
            this.bunifuMail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuMail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuMail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuMail.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(162)))), ((int)(((byte)(89)))));
            this.bunifuMail.BorderRadius = 35;
            this.bunifuMail.BorderThickness = 2;
            this.bunifuMail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuMail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuMail.DefaultFont = new System.Drawing.Font("Segoe UI Black", 15.75F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuMail.DefaultText = "";
            this.bunifuMail.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(226)))), ((int)(((byte)(133)))));
            this.bunifuMail.HideSelection = true;
            this.bunifuMail.IconLeft = null;
            this.bunifuMail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuMail.IconPadding = 10;
            this.bunifuMail.IconRight = null;
            this.bunifuMail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuMail.Lines = new string[0];
            this.bunifuMail.Location = new System.Drawing.Point(22, 276);
            this.bunifuMail.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.bunifuMail.MaxLength = 32767;
            this.bunifuMail.MinimumSize = new System.Drawing.Size(2, 1);
            this.bunifuMail.Modified = false;
            this.bunifuMail.Multiline = false;
            this.bunifuMail.Name = "bunifuMail";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuMail.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuMail.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuMail.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(162)))), ((int)(((byte)(89)))));
            stateProperties4.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(226)))), ((int)(((byte)(133)))));
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuMail.OnIdleState = stateProperties4;
            this.bunifuMail.Padding = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.bunifuMail.PasswordChar = '\0';
            this.bunifuMail.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(41)))), ((int)(((byte)(54)))));
            this.bunifuMail.PlaceholderText = "examplemail@email.az";
            this.bunifuMail.ReadOnly = false;
            this.bunifuMail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuMail.SelectedText = "";
            this.bunifuMail.SelectionLength = 0;
            this.bunifuMail.SelectionStart = 0;
            this.bunifuMail.ShortcutsEnabled = true;
            this.bunifuMail.Size = new System.Drawing.Size(278, 56);
            this.bunifuMail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bunifuMail.TabIndex = 3;
            this.bunifuMail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuMail.TextMarginBottom = 0;
            this.bunifuMail.TextMarginLeft = 3;
            this.bunifuMail.TextMarginTop = 0;
            this.bunifuMail.TextPlaceholder = "examplemail@email.az";
            this.bunifuMail.UseSystemPasswordChar = false;
            this.bunifuMail.WordWrap = true;
            // 
            // bunifuSurnamelbl
            // 
            this.bunifuSurnamelbl.AcceptsReturn = false;
            this.bunifuSurnamelbl.AcceptsTab = false;
            this.bunifuSurnamelbl.AnimationSpeed = 200;
            this.bunifuSurnamelbl.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuSurnamelbl.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuSurnamelbl.BackColor = System.Drawing.Color.Transparent;
            this.bunifuSurnamelbl.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSurnamelbl.BackgroundImage")));
            this.bunifuSurnamelbl.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuSurnamelbl.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuSurnamelbl.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuSurnamelbl.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(162)))), ((int)(((byte)(89)))));
            this.bunifuSurnamelbl.BorderRadius = 35;
            this.bunifuSurnamelbl.BorderThickness = 2;
            this.bunifuSurnamelbl.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuSurnamelbl.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuSurnamelbl.DefaultFont = new System.Drawing.Font("Segoe UI Black", 15.75F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuSurnamelbl.DefaultText = "";
            this.bunifuSurnamelbl.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(226)))), ((int)(((byte)(133)))));
            this.bunifuSurnamelbl.HideSelection = true;
            this.bunifuSurnamelbl.IconLeft = null;
            this.bunifuSurnamelbl.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuSurnamelbl.IconPadding = 10;
            this.bunifuSurnamelbl.IconRight = null;
            this.bunifuSurnamelbl.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuSurnamelbl.Lines = new string[0];
            this.bunifuSurnamelbl.Location = new System.Drawing.Point(22, 169);
            this.bunifuSurnamelbl.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.bunifuSurnamelbl.MaxLength = 32767;
            this.bunifuSurnamelbl.MinimumSize = new System.Drawing.Size(2, 1);
            this.bunifuSurnamelbl.Modified = false;
            this.bunifuSurnamelbl.Multiline = false;
            this.bunifuSurnamelbl.Name = "bunifuSurnamelbl";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuSurnamelbl.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuSurnamelbl.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuSurnamelbl.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(162)))), ((int)(((byte)(89)))));
            stateProperties8.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(226)))), ((int)(((byte)(133)))));
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuSurnamelbl.OnIdleState = stateProperties8;
            this.bunifuSurnamelbl.Padding = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.bunifuSurnamelbl.PasswordChar = '\0';
            this.bunifuSurnamelbl.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(41)))), ((int)(((byte)(54)))));
            this.bunifuSurnamelbl.PlaceholderText = "Surname";
            this.bunifuSurnamelbl.ReadOnly = false;
            this.bunifuSurnamelbl.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuSurnamelbl.SelectedText = "";
            this.bunifuSurnamelbl.SelectionLength = 0;
            this.bunifuSurnamelbl.SelectionStart = 0;
            this.bunifuSurnamelbl.ShortcutsEnabled = true;
            this.bunifuSurnamelbl.Size = new System.Drawing.Size(278, 56);
            this.bunifuSurnamelbl.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bunifuSurnamelbl.TabIndex = 2;
            this.bunifuSurnamelbl.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuSurnamelbl.TextMarginBottom = 0;
            this.bunifuSurnamelbl.TextMarginLeft = 3;
            this.bunifuSurnamelbl.TextMarginTop = 0;
            this.bunifuSurnamelbl.TextPlaceholder = "Surname";
            this.bunifuSurnamelbl.UseSystemPasswordChar = false;
            this.bunifuSurnamelbl.WordWrap = true;
            // 
            // bunifuTextBox1
            // 
            this.bunifuTextBox1.AcceptsReturn = false;
            this.bunifuTextBox1.AcceptsTab = false;
            this.bunifuTextBox1.AnimationSpeed = 200;
            this.bunifuTextBox1.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBox1.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBox1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuTextBox1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox1.BackgroundImage")));
            this.bunifuTextBox1.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBox1.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBox1.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBox1.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(162)))), ((int)(((byte)(89)))));
            this.bunifuTextBox1.BorderRadius = 35;
            this.bunifuTextBox1.BorderThickness = 2;
            this.bunifuTextBox1.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBox1.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox1.DefaultFont = new System.Drawing.Font("Segoe UI Black", 15.75F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuTextBox1.DefaultText = "";
            this.bunifuTextBox1.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(226)))), ((int)(((byte)(133)))));
            this.bunifuTextBox1.HideSelection = true;
            this.bunifuTextBox1.IconLeft = null;
            this.bunifuTextBox1.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox1.IconPadding = 10;
            this.bunifuTextBox1.IconRight = null;
            this.bunifuTextBox1.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox1.Lines = new string[0];
            this.bunifuTextBox1.Location = new System.Drawing.Point(22, 62);
            this.bunifuTextBox1.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.bunifuTextBox1.MaxLength = 32767;
            this.bunifuTextBox1.MinimumSize = new System.Drawing.Size(2, 1);
            this.bunifuTextBox1.Modified = false;
            this.bunifuTextBox1.Multiline = false;
            this.bunifuTextBox1.Name = "bunifuTextBox1";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox1.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBox1.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox1.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(162)))), ((int)(((byte)(89)))));
            stateProperties12.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(226)))), ((int)(((byte)(133)))));
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox1.OnIdleState = stateProperties12;
            this.bunifuTextBox1.Padding = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.bunifuTextBox1.PasswordChar = '\0';
            this.bunifuTextBox1.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(41)))), ((int)(((byte)(54)))));
            this.bunifuTextBox1.PlaceholderText = "Name";
            this.bunifuTextBox1.ReadOnly = false;
            this.bunifuTextBox1.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBox1.SelectedText = "";
            this.bunifuTextBox1.SelectionLength = 0;
            this.bunifuTextBox1.SelectionStart = 0;
            this.bunifuTextBox1.ShortcutsEnabled = true;
            this.bunifuTextBox1.Size = new System.Drawing.Size(278, 56);
            this.bunifuTextBox1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bunifuTextBox1.TabIndex = 1;
            this.bunifuTextBox1.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBox1.TextMarginBottom = 0;
            this.bunifuTextBox1.TextMarginLeft = 3;
            this.bunifuTextBox1.TextMarginTop = 0;
            this.bunifuTextBox1.TextPlaceholder = "Name";
            this.bunifuTextBox1.UseSystemPasswordChar = false;
            this.bunifuTextBox1.WordWrap = true;
            this.bunifuTextBox1.TextChanged += new System.EventHandler(this.bunifuTextBox1_TextChanged);
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = true;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(41)))), ((int)(((byte)(54)))));
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "EXIT";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges2;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Segoe UI", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton1.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton1.IdleBorderRadius = 31;
            this.bunifuButton1.IdleBorderThickness = 1;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(41)))), ((int)(((byte)(54)))));
            this.bunifuButton1.IdleIconLeftImage = null;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(862, 12);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 1;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.BorderRadius = 1;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton1.OnIdleState.BorderRadius = 1;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(41)))), ((int)(((byte)(54)))));
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnIdleState.IconLeftImage = null;
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.BorderRadius = 1;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(62, 33);
            this.bunifuButton1.TabIndex = 13;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.TopRight;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            this.bunifuButton1.Click += new System.EventHandler(this.bunifuButton1_Click);
            // 
            // guna2AnimateWindow1
            // 
            this.guna2AnimateWindow1.Interval = 1000;
            this.guna2AnimateWindow1.TargetForm = this;
            // 
            // dateTimePicker1
            // 
            this.dateTimePicker1.CalendarFont = new System.Drawing.Font("Microsoft Sans Serif", 13F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dateTimePicker1.CalendarForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(226)))), ((int)(((byte)(133)))));
            this.dateTimePicker1.CalendarMonthBackground = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(226)))), ((int)(((byte)(133)))));
            this.dateTimePicker1.CalendarTitleBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(226)))), ((int)(((byte)(133)))));
            this.dateTimePicker1.CalendarTitleForeColor = System.Drawing.SystemColors.ActiveCaption;
            this.dateTimePicker1.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dateTimePicker1.Location = new System.Drawing.Point(25, 444);
            this.dateTimePicker1.MaxDate = new System.DateTime(2003, 7, 31, 0, 0, 0, 0);
            this.dateTimePicker1.Name = "dateTimePicker1";
            this.dateTimePicker1.Size = new System.Drawing.Size(275, 24);
            this.dateTimePicker1.TabIndex = 5;
            this.dateTimePicker1.Value = new System.DateTime(2003, 7, 31, 0, 0, 0, 0);
            this.dateTimePicker1.ValueChanged += new System.EventHandler(this.dateTimePicker1_ValueChanged);
            // 
            // listBox1
            // 
            this.listBox1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(226)))), ((int)(((byte)(133)))));
            this.listBox1.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.listBox1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(41)))), ((int)(((byte)(54)))));
            this.listBox1.FormattingEnabled = true;
            this.listBox1.ItemHeight = 15;
            this.listBox1.Location = new System.Drawing.Point(485, 48);
            this.listBox1.Name = "listBox1";
            this.listBox1.Size = new System.Drawing.Size(431, 407);
            this.listBox1.TabIndex = 12;
            this.listBox1.SelectedIndexChanged += new System.EventHandler(this.listBox1_SelectedIndexChanged);
            // 
            // bunifuFileNametxt
            // 
            this.bunifuFileNametxt.AcceptsReturn = false;
            this.bunifuFileNametxt.AcceptsTab = false;
            this.bunifuFileNametxt.AnimationSpeed = 200;
            this.bunifuFileNametxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuFileNametxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuFileNametxt.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFileNametxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuFileNametxt.BackgroundImage")));
            this.bunifuFileNametxt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuFileNametxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuFileNametxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuFileNametxt.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(162)))), ((int)(((byte)(89)))));
            this.bunifuFileNametxt.BorderRadius = 35;
            this.bunifuFileNametxt.BorderThickness = 2;
            this.bunifuFileNametxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuFileNametxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuFileNametxt.DefaultFont = new System.Drawing.Font("Segoe UI Black", 15.75F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuFileNametxt.DefaultText = "";
            this.bunifuFileNametxt.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(226)))), ((int)(((byte)(133)))));
            this.bunifuFileNametxt.HideSelection = true;
            this.bunifuFileNametxt.IconLeft = null;
            this.bunifuFileNametxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuFileNametxt.IconPadding = 10;
            this.bunifuFileNametxt.IconRight = null;
            this.bunifuFileNametxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuFileNametxt.Lines = new string[0];
            this.bunifuFileNametxt.Location = new System.Drawing.Point(591, 479);
            this.bunifuFileNametxt.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.bunifuFileNametxt.MaxLength = 32767;
            this.bunifuFileNametxt.MinimumSize = new System.Drawing.Size(2, 1);
            this.bunifuFileNametxt.Modified = false;
            this.bunifuFileNametxt.Multiline = false;
            this.bunifuFileNametxt.Name = "bunifuFileNametxt";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuFileNametxt.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuFileNametxt.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuFileNametxt.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(162)))), ((int)(((byte)(89)))));
            stateProperties16.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(226)))), ((int)(((byte)(133)))));
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuFileNametxt.OnIdleState = stateProperties16;
            this.bunifuFileNametxt.Padding = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.bunifuFileNametxt.PasswordChar = '\0';
            this.bunifuFileNametxt.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(41)))), ((int)(((byte)(54)))));
            this.bunifuFileNametxt.PlaceholderText = "example.json";
            this.bunifuFileNametxt.ReadOnly = false;
            this.bunifuFileNametxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuFileNametxt.SelectedText = "";
            this.bunifuFileNametxt.SelectionLength = 0;
            this.bunifuFileNametxt.SelectionStart = 0;
            this.bunifuFileNametxt.ShortcutsEnabled = true;
            this.bunifuFileNametxt.Size = new System.Drawing.Size(249, 56);
            this.bunifuFileNametxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bunifuFileNametxt.TabIndex = 10;
            this.bunifuFileNametxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuFileNametxt.TextMarginBottom = 0;
            this.bunifuFileNametxt.TextMarginLeft = 3;
            this.bunifuFileNametxt.TextMarginTop = 0;
            this.bunifuFileNametxt.TextPlaceholder = "example.json";
            this.bunifuFileNametxt.UseSystemPasswordChar = false;
            this.bunifuFileNametxt.WordWrap = true;
            this.bunifuFileNametxt.TextChanged += new System.EventHandler(this.bunifuFileNametxt_TextChanged);
            // 
            // bunifuLoadbtn
            // 
            this.bunifuLoadbtn.AllowAnimations = true;
            this.bunifuLoadbtn.AllowMouseEffects = true;
            this.bunifuLoadbtn.AllowToggling = false;
            this.bunifuLoadbtn.AnimationSpeed = 200;
            this.bunifuLoadbtn.AutoGenerateColors = false;
            this.bunifuLoadbtn.AutoRoundBorders = true;
            this.bunifuLoadbtn.AutoSizeLeftIcon = true;
            this.bunifuLoadbtn.AutoSizeRightIcon = true;
            this.bunifuLoadbtn.BackColor = System.Drawing.Color.Transparent;
            this.bunifuLoadbtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(166)))), ((int)(((byte)(61)))), ((int)(((byte)(64)))));
            this.bunifuLoadbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuLoadbtn.BackgroundImage")));
            this.bunifuLoadbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuLoadbtn.ButtonText = "Load";
            this.bunifuLoadbtn.ButtonTextMarginLeft = 0;
            this.bunifuLoadbtn.ColorContrastOnClick = 45;
            this.bunifuLoadbtn.ColorContrastOnHover = 45;
            this.bunifuLoadbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.bunifuLoadbtn.CustomizableEdges = borderEdges6;
            this.bunifuLoadbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuLoadbtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuLoadbtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuLoadbtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuLoadbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuLoadbtn.Font = new System.Drawing.Font("Segoe UI", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLoadbtn.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(233)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.bunifuLoadbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuLoadbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLoadbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuLoadbtn.IconMarginLeft = 11;
            this.bunifuLoadbtn.IconPadding = 10;
            this.bunifuLoadbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuLoadbtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLoadbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuLoadbtn.IconSize = 25;
            this.bunifuLoadbtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuLoadbtn.IdleBorderRadius = 54;
            this.bunifuLoadbtn.IdleBorderThickness = 1;
            this.bunifuLoadbtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(166)))), ((int)(((byte)(61)))), ((int)(((byte)(64)))));
            this.bunifuLoadbtn.IdleIconLeftImage = null;
            this.bunifuLoadbtn.IdleIconRightImage = null;
            this.bunifuLoadbtn.IndicateFocus = false;
            this.bunifuLoadbtn.Location = new System.Drawing.Point(507, 479);
            this.bunifuLoadbtn.Name = "bunifuLoadbtn";
            this.bunifuLoadbtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuLoadbtn.OnDisabledState.BorderRadius = 1;
            this.bunifuLoadbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuLoadbtn.OnDisabledState.BorderThickness = 1;
            this.bunifuLoadbtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuLoadbtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuLoadbtn.OnDisabledState.IconLeftImage = null;
            this.bunifuLoadbtn.OnDisabledState.IconRightImage = null;
            this.bunifuLoadbtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuLoadbtn.onHoverState.BorderRadius = 1;
            this.bunifuLoadbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuLoadbtn.onHoverState.BorderThickness = 1;
            this.bunifuLoadbtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuLoadbtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuLoadbtn.onHoverState.IconLeftImage = null;
            this.bunifuLoadbtn.onHoverState.IconRightImage = null;
            this.bunifuLoadbtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuLoadbtn.OnIdleState.BorderRadius = 1;
            this.bunifuLoadbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuLoadbtn.OnIdleState.BorderThickness = 1;
            this.bunifuLoadbtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(166)))), ((int)(((byte)(61)))), ((int)(((byte)(64)))));
            this.bunifuLoadbtn.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(233)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.bunifuLoadbtn.OnIdleState.IconLeftImage = null;
            this.bunifuLoadbtn.OnIdleState.IconRightImage = null;
            this.bunifuLoadbtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuLoadbtn.OnPressedState.BorderRadius = 1;
            this.bunifuLoadbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuLoadbtn.OnPressedState.BorderThickness = 1;
            this.bunifuLoadbtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuLoadbtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuLoadbtn.OnPressedState.IconLeftImage = null;
            this.bunifuLoadbtn.OnPressedState.IconRightImage = null;
            this.bunifuLoadbtn.Size = new System.Drawing.Size(77, 56);
            this.bunifuLoadbtn.TabIndex = 9;
            this.bunifuLoadbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuLoadbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuLoadbtn.TextMarginLeft = 0;
            this.bunifuLoadbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuLoadbtn.UseDefaultRadiusAndThickness = true;
            this.bunifuLoadbtn.Click += new System.EventHandler(this.bunifuLoadbtn_Click);
            // 
            // bunifuAddbtn
            // 
            this.bunifuAddbtn.AllowAnimations = true;
            this.bunifuAddbtn.AllowMouseEffects = true;
            this.bunifuAddbtn.AllowToggling = false;
            this.bunifuAddbtn.AnimationSpeed = 200;
            this.bunifuAddbtn.AutoGenerateColors = false;
            this.bunifuAddbtn.AutoRoundBorders = true;
            this.bunifuAddbtn.AutoSizeLeftIcon = true;
            this.bunifuAddbtn.AutoSizeRightIcon = true;
            this.bunifuAddbtn.BackColor = System.Drawing.Color.Transparent;
            this.bunifuAddbtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(130)))), ((int)(((byte)(162)))));
            this.bunifuAddbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuAddbtn.BackgroundImage")));
            this.bunifuAddbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuAddbtn.ButtonText = "Add";
            this.bunifuAddbtn.ButtonTextMarginLeft = 0;
            this.bunifuAddbtn.ColorContrastOnClick = 45;
            this.bunifuAddbtn.ColorContrastOnHover = 45;
            this.bunifuAddbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.bunifuAddbtn.CustomizableEdges = borderEdges5;
            this.bunifuAddbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuAddbtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuAddbtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuAddbtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuAddbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuAddbtn.Font = new System.Drawing.Font("Segoe UI", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuAddbtn.ForeColor = System.Drawing.Color.White;
            this.bunifuAddbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuAddbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuAddbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuAddbtn.IconMarginLeft = 11;
            this.bunifuAddbtn.IconPadding = 10;
            this.bunifuAddbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuAddbtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuAddbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuAddbtn.IconSize = 25;
            this.bunifuAddbtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuAddbtn.IdleBorderRadius = 54;
            this.bunifuAddbtn.IdleBorderThickness = 1;
            this.bunifuAddbtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(130)))), ((int)(((byte)(162)))));
            this.bunifuAddbtn.IdleIconLeftImage = null;
            this.bunifuAddbtn.IdleIconRightImage = null;
            this.bunifuAddbtn.IndicateFocus = false;
            this.bunifuAddbtn.Location = new System.Drawing.Point(344, 479);
            this.bunifuAddbtn.Name = "bunifuAddbtn";
            this.bunifuAddbtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuAddbtn.OnDisabledState.BorderRadius = 1;
            this.bunifuAddbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuAddbtn.OnDisabledState.BorderThickness = 1;
            this.bunifuAddbtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuAddbtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuAddbtn.OnDisabledState.IconLeftImage = null;
            this.bunifuAddbtn.OnDisabledState.IconRightImage = null;
            this.bunifuAddbtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuAddbtn.onHoverState.BorderRadius = 1;
            this.bunifuAddbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuAddbtn.onHoverState.BorderThickness = 1;
            this.bunifuAddbtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuAddbtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuAddbtn.onHoverState.IconLeftImage = null;
            this.bunifuAddbtn.onHoverState.IconRightImage = null;
            this.bunifuAddbtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuAddbtn.OnIdleState.BorderRadius = 1;
            this.bunifuAddbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuAddbtn.OnIdleState.BorderThickness = 1;
            this.bunifuAddbtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(130)))), ((int)(((byte)(162)))));
            this.bunifuAddbtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuAddbtn.OnIdleState.IconLeftImage = null;
            this.bunifuAddbtn.OnIdleState.IconRightImage = null;
            this.bunifuAddbtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuAddbtn.OnPressedState.BorderRadius = 1;
            this.bunifuAddbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuAddbtn.OnPressedState.BorderThickness = 1;
            this.bunifuAddbtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuAddbtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuAddbtn.OnPressedState.IconLeftImage = null;
            this.bunifuAddbtn.OnPressedState.IconRightImage = null;
            this.bunifuAddbtn.Size = new System.Drawing.Size(141, 56);
            this.bunifuAddbtn.TabIndex = 8;
            this.bunifuAddbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuAddbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuAddbtn.TextMarginLeft = 0;
            this.bunifuAddbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuAddbtn.UseDefaultRadiusAndThickness = true;
            this.bunifuAddbtn.Click += new System.EventHandler(this.bunifuAddbtn_Click);
            // 
            // bunifuModifybtn
            // 
            this.bunifuModifybtn.AllowAnimations = true;
            this.bunifuModifybtn.AllowMouseEffects = true;
            this.bunifuModifybtn.AllowToggling = false;
            this.bunifuModifybtn.AnimationSpeed = 200;
            this.bunifuModifybtn.AutoGenerateColors = false;
            this.bunifuModifybtn.AutoRoundBorders = true;
            this.bunifuModifybtn.AutoSizeLeftIcon = true;
            this.bunifuModifybtn.AutoSizeRightIcon = true;
            this.bunifuModifybtn.BackColor = System.Drawing.Color.Transparent;
            this.bunifuModifybtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(130)))), ((int)(((byte)(162)))));
            this.bunifuModifybtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuModifybtn.BackgroundImage")));
            this.bunifuModifybtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuModifybtn.ButtonText = "Modify";
            this.bunifuModifybtn.ButtonTextMarginLeft = 0;
            this.bunifuModifybtn.ColorContrastOnClick = 45;
            this.bunifuModifybtn.ColorContrastOnHover = 45;
            this.bunifuModifybtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.bunifuModifybtn.CustomizableEdges = borderEdges4;
            this.bunifuModifybtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuModifybtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuModifybtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuModifybtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuModifybtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuModifybtn.Font = new System.Drawing.Font("Segoe UI", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuModifybtn.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(105)))), ((int)(((byte)(0)))));
            this.bunifuModifybtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuModifybtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuModifybtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuModifybtn.IconMarginLeft = 11;
            this.bunifuModifybtn.IconPadding = 10;
            this.bunifuModifybtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuModifybtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuModifybtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuModifybtn.IconSize = 25;
            this.bunifuModifybtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuModifybtn.IdleBorderRadius = 54;
            this.bunifuModifybtn.IdleBorderThickness = 1;
            this.bunifuModifybtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(130)))), ((int)(((byte)(162)))));
            this.bunifuModifybtn.IdleIconLeftImage = null;
            this.bunifuModifybtn.IdleIconRightImage = null;
            this.bunifuModifybtn.IndicateFocus = false;
            this.bunifuModifybtn.Location = new System.Drawing.Point(172, 479);
            this.bunifuModifybtn.Name = "bunifuModifybtn";
            this.bunifuModifybtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuModifybtn.OnDisabledState.BorderRadius = 1;
            this.bunifuModifybtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuModifybtn.OnDisabledState.BorderThickness = 1;
            this.bunifuModifybtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuModifybtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuModifybtn.OnDisabledState.IconLeftImage = null;
            this.bunifuModifybtn.OnDisabledState.IconRightImage = null;
            this.bunifuModifybtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuModifybtn.onHoverState.BorderRadius = 1;
            this.bunifuModifybtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuModifybtn.onHoverState.BorderThickness = 1;
            this.bunifuModifybtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuModifybtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuModifybtn.onHoverState.IconLeftImage = null;
            this.bunifuModifybtn.onHoverState.IconRightImage = null;
            this.bunifuModifybtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuModifybtn.OnIdleState.BorderRadius = 1;
            this.bunifuModifybtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuModifybtn.OnIdleState.BorderThickness = 1;
            this.bunifuModifybtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(130)))), ((int)(((byte)(162)))));
            this.bunifuModifybtn.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(105)))), ((int)(((byte)(0)))));
            this.bunifuModifybtn.OnIdleState.IconLeftImage = null;
            this.bunifuModifybtn.OnIdleState.IconRightImage = null;
            this.bunifuModifybtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuModifybtn.OnPressedState.BorderRadius = 1;
            this.bunifuModifybtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuModifybtn.OnPressedState.BorderThickness = 1;
            this.bunifuModifybtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuModifybtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuModifybtn.OnPressedState.IconLeftImage = null;
            this.bunifuModifybtn.OnPressedState.IconRightImage = null;
            this.bunifuModifybtn.Size = new System.Drawing.Size(141, 56);
            this.bunifuModifybtn.TabIndex = 7;
            this.bunifuModifybtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuModifybtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuModifybtn.TextMarginLeft = 0;
            this.bunifuModifybtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuModifybtn.UseDefaultRadiusAndThickness = true;
            this.bunifuModifybtn.Click += new System.EventHandler(this.bunifuModifybtn_Click);
            // 
            // bunifuClearbtn
            // 
            this.bunifuClearbtn.AllowAnimations = true;
            this.bunifuClearbtn.AllowMouseEffects = true;
            this.bunifuClearbtn.AllowToggling = false;
            this.bunifuClearbtn.AnimationSpeed = 200;
            this.bunifuClearbtn.AutoGenerateColors = false;
            this.bunifuClearbtn.AutoRoundBorders = true;
            this.bunifuClearbtn.AutoSizeLeftIcon = true;
            this.bunifuClearbtn.AutoSizeRightIcon = true;
            this.bunifuClearbtn.BackColor = System.Drawing.Color.Transparent;
            this.bunifuClearbtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(130)))), ((int)(((byte)(162)))));
            this.bunifuClearbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuClearbtn.BackgroundImage")));
            this.bunifuClearbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuClearbtn.ButtonText = "Clear";
            this.bunifuClearbtn.ButtonTextMarginLeft = 0;
            this.bunifuClearbtn.ColorContrastOnClick = 45;
            this.bunifuClearbtn.ColorContrastOnHover = 45;
            this.bunifuClearbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.bunifuClearbtn.CustomizableEdges = borderEdges3;
            this.bunifuClearbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuClearbtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuClearbtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuClearbtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuClearbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuClearbtn.Font = new System.Drawing.Font("Segoe UI", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuClearbtn.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(195)))), ((int)(((byte)(247)))), ((int)(((byte)(58)))));
            this.bunifuClearbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuClearbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuClearbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuClearbtn.IconMarginLeft = 11;
            this.bunifuClearbtn.IconPadding = 10;
            this.bunifuClearbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuClearbtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuClearbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuClearbtn.IconSize = 25;
            this.bunifuClearbtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuClearbtn.IdleBorderRadius = 54;
            this.bunifuClearbtn.IdleBorderThickness = 1;
            this.bunifuClearbtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(130)))), ((int)(((byte)(162)))));
            this.bunifuClearbtn.IdleIconLeftImage = null;
            this.bunifuClearbtn.IdleIconRightImage = null;
            this.bunifuClearbtn.IndicateFocus = false;
            this.bunifuClearbtn.Location = new System.Drawing.Point(12, 479);
            this.bunifuClearbtn.Name = "bunifuClearbtn";
            this.bunifuClearbtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuClearbtn.OnDisabledState.BorderRadius = 1;
            this.bunifuClearbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuClearbtn.OnDisabledState.BorderThickness = 1;
            this.bunifuClearbtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuClearbtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuClearbtn.OnDisabledState.IconLeftImage = null;
            this.bunifuClearbtn.OnDisabledState.IconRightImage = null;
            this.bunifuClearbtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuClearbtn.onHoverState.BorderRadius = 1;
            this.bunifuClearbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuClearbtn.onHoverState.BorderThickness = 1;
            this.bunifuClearbtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuClearbtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuClearbtn.onHoverState.IconLeftImage = null;
            this.bunifuClearbtn.onHoverState.IconRightImage = null;
            this.bunifuClearbtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuClearbtn.OnIdleState.BorderRadius = 1;
            this.bunifuClearbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuClearbtn.OnIdleState.BorderThickness = 1;
            this.bunifuClearbtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(130)))), ((int)(((byte)(162)))));
            this.bunifuClearbtn.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(195)))), ((int)(((byte)(247)))), ((int)(((byte)(58)))));
            this.bunifuClearbtn.OnIdleState.IconLeftImage = null;
            this.bunifuClearbtn.OnIdleState.IconRightImage = null;
            this.bunifuClearbtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuClearbtn.OnPressedState.BorderRadius = 1;
            this.bunifuClearbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuClearbtn.OnPressedState.BorderThickness = 1;
            this.bunifuClearbtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuClearbtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuClearbtn.OnPressedState.IconLeftImage = null;
            this.bunifuClearbtn.OnPressedState.IconRightImage = null;
            this.bunifuClearbtn.Size = new System.Drawing.Size(141, 56);
            this.bunifuClearbtn.TabIndex = 6;
            this.bunifuClearbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuClearbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuClearbtn.TextMarginLeft = 0;
            this.bunifuClearbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuClearbtn.UseDefaultRadiusAndThickness = true;
            this.bunifuClearbtn.Click += new System.EventHandler(this.bunifuClearbtn_Click);
            // 
            // examplelbl
            // 
            this.examplelbl.AllowParentOverrides = false;
            this.examplelbl.AutoEllipsis = false;
            this.examplelbl.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(10)))), ((int)(((byte)(17)))), ((int)(((byte)(40)))));
            this.examplelbl.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.examplelbl.Cursor = System.Windows.Forms.Cursors.Default;
            this.examplelbl.CursorType = System.Windows.Forms.Cursors.Default;
            this.examplelbl.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.examplelbl.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(130)))), ((int)(((byte)(162)))));
            this.examplelbl.Location = new System.Drawing.Point(604, 456);
            this.examplelbl.Name = "examplelbl";
            this.examplelbl.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.examplelbl.Size = new System.Drawing.Size(131, 23);
            this.examplelbl.TabIndex = 14;
            this.examplelbl.Text = "Enter File Name :";
            this.examplelbl.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.examplelbl.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // Form3
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(31)))), ((int)(((byte)(84)))));
            this.ClientSize = new System.Drawing.Size(936, 547);
            this.Controls.Add(this.examplelbl);
            this.Controls.Add(this.bunifuClearbtn);
            this.Controls.Add(this.bunifuModifybtn);
            this.Controls.Add(this.bunifuAddbtn);
            this.Controls.Add(this.bunifuLoadbtn);
            this.Controls.Add(this.bunifuFileNametxt);
            this.Controls.Add(this.listBox1);
            this.Controls.Add(this.dateTimePicker1);
            this.Controls.Add(this.bunifuSavebtn);
            this.Controls.Add(this.bunifuMaillbl);
            this.Controls.Add(this.maskedTextBox1);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.bunifuNamelbl);
            this.Controls.Add(this.bunifuNumberlbl);
            this.Controls.Add(this.bunifuMail);
            this.Controls.Add(this.bunifuSurnamelbl);
            this.Controls.Add(this.bunifuTextBox1);
            this.Controls.Add(this.bunifuButton1);
            this.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.Name = "Form3";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "     ";
            this.Load += new System.EventHandler(this.Form3_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox1;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuSurnamelbl;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuMail;
        private Bunifu.UI.WinForms.BunifuLabel bunifuNumberlbl;
        private Bunifu.UI.WinForms.BunifuLabel bunifuNamelbl;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private System.Windows.Forms.MaskedTextBox maskedTextBox1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuMaillbl;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuSavebtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Guna.UI2.WinForms.Guna2AnimateWindow guna2AnimateWindow1;
        private System.Windows.Forms.ListBox listBox1;
        private System.Windows.Forms.DateTimePicker dateTimePicker1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuClearbtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuModifybtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuAddbtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuLoadbtn;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuFileNametxt;
        private Bunifu.UI.WinForms.BunifuLabel examplelbl;
    }
}